version: "3.8"

services:

  makemake:
    image: pmaterer/makemake
    build:
      context: .
    container_name: makemake
    environment: 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
      DB_ENGINE: ${DB_ENGINE}
    ports:
    - 8080:8080
    networks:
    - makemake
    restart: always

  db:
    image: postgres:13.0
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
    - postgres:/data/postgres
    ports:
    - 5432:5432
    networks:
    - makemake
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:4.27
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
    - pgadmin:/root/.pgadmin
    ports:
    - 5050:80
    networks:
    - makemake
    restart: unless-stopped

networks:
  makemake:
    driver: bridge

volumes:
  postgres:
  pgadmin: